### ISSUE TITLE
racket.models not found exception is thrown for command racket init

### ISSUE THREAD

**Issue by prakashdaleyardi** [carlomazzaferro/racket#1] opened 2019-06-04 09:56 UTC
* racket version: built from github repo
* Python version: 3.6
* Operating System: Windows 10

### Description
Following exception is thrown when executing racket init
ModuleNotFoundError: No module named 'racket.models'

(crmair2) C:\rkt>racket init --name demo --path demo
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\crmair2\Scripts\racket-script.py", line 11, in <module>
    load_entry_point('racket==0.3.7', 'console_scripts', 'racket')()
  File "C:\ProgramData\Anaconda3\envs\crmair2\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\ProgramData\Anaconda3\envs\crmair2\lib\site-packages\pkg_resources\__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "C:\ProgramData\Anaconda3\envs\crmair2\lib\site-packages\pkg_resources\__init__.py", line 2434, in load
    return self.resolve()
  File "C:\ProgramData\Anaconda3\envs\crmair2\lib\site-packages\pkg_resources\__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\programdata\anaconda3\envs\crmair2\lib\site-packages\racket-0.3.7-py3.6.egg\racket\__init__.py", line 2, in <module>
    from racket.models.learner.base import Learner
ModuleNotFoundError: No module named 'racket.models'

### What I Did
1. Cloned github repo
2. python setup.py install
3. racket init --name demo --path demo
```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by carlomazzaferro** [comment] 2019-06-04 14:17
Temporary fix: `pip install -e .` from the root directory. 

I'll investigate this further once I get some time, and in fact I was able to reproduce the error on a mac.

**Comment by prakashdaleyardi** [comment] 2019-06-05 07:21
**Thanks for the solution. It did fix the issue.** 
But ran into below thereafter. 
`UnicodeEncodeError: 'charmap' codec can't encode character '\u256a' in position 1: character maps to <undefined>`

Resolved this by adding try-catch at project.py->Line#85 and then copying below files manually.
\extras/TEST.jpg
\serialized/base/1/variables/variables.data-00000-of-00001
\demo\serialized/base/1/variables/variables.index
\serialized/base/1/saved_model.pb
\serialized/base_1.h5
\web\static/js/1.a95de961.chunk.js.map

But thereafter docker-compose showed below error.
```
(crmair2) C:\racket\demo\demo\demo>docker-compose up --build -d
Creating network "demo_default" with the default driver
Building tf-serving
ERROR: Dockerfile parse error line 29: unknown instruction: CA-CERTIFICATES
```

**Comment by prakashdaleyardi** [comment] 2019-06-05 08:20
One more thing I forgot to mention:
I had to change the version line in docker-compose.yaml to `version: '2.1'`. Otherwise, it throws below error.
`ERROR: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version`

**Comment by carlomazzaferro** [comment] 2019-06-06 13:47
I'll push updates for the Dockerfile.tfserving, and updated docker-compose versions. . They recently released an official image that doesn't require building straight from Ubuntu. Tested locally, it should work. As far as the charmap error, can't tell what's causing it and can't reproduce. 

Can you test changing line #85 to this? 

```
with open(os.path.join(cls.RACKET_DIR, file_path, encoding="utf-8"), 'w') as f:
     f.write(data.decode('utf-8'))
```

**Comment by prakashdaleyardi** [comment] 2019-06-07 09:55
I tried this but it did not work. 
Also tried with `open(os.path.join(cls.RACKET_DIR, file_path), 'w', encoding="utf-8") as f:` but not worked.

I took latest from github and ran `pip install -e .` 
Thereafter `python init --name test1` throws new error `ModuleNotFoundError: No module named 'gevent'`. Installed gevent to get past this issue.

**Comment by prakashdaleyardi** [comment] 2019-06-07 10:35
`docker-compose up --build -d` failed with error `ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements/base.txt' `. Copied requirements folder manually to the project folder and ran the command again. But it failed with following error:
```
Step 5/9 : RUN find . -name '*.pyc' -delete
 ---> Running in 1914fd8859d7
File not found - *.pyc
```

**Comment by carlomazzaferro** [comment] 2019-06-07 18:24
Alright, should be fixed. I messed up one of the commits for the Dockerfile but should be gtg now. I added gevent for the serving portion, added that to the requirements as well.

**Comment by prakashdaleyardi** [comment] 2019-06-10 06:03
With latest code, getting below error for `racket init --name test1`
`AttributeError: module 'tensorflow' has no attribute 'python'`

**Comment by carlomazzaferro** [comment] 2019-06-10 15:01
Fixed. Build & tests passing, so you should see some more stability now. I probably should've given more thought before upgrading the TF version but it was overdue for some time now.

**Comment by prakashdaleyardi** [comment] 2019-06-11 03:51
`racket init --name test1` threw below error
`UnicodeEncodeError: 'charmap' codec can't encode character '\u21e7'`
Noticed that `except UnicodeDecodeError` block did not handle the file _1.a95de961.chunk.js.map_
So I changed line#84, added `encoding='utf-8'`, as below:
`with open(os.path.join(cls.RACKET_DIR, file_path), 'w', encoding='utf-8') as f:`

It fixed the issue of `racket init`.

But thereafter, docker-compose caused below issue:
```
(crmair2) C:\racket\test1>docker-compose up --build -d
Building tf-serving
ERROR: Dockerfile parse error line 20: unknown instruction: TENSORFLOW_MODEL_SERVER
```
To get past this issue, I copied the content of Dockerfile.tfserving to Notepad and saved again. 
Docker compose, thereafter, produced below error:
```
(crmair2) C:\racket\test1>docker-compose up --build -d
Building tf-serving
Step 1/8 : FROM tensorflow/serving
 ---> 38bee21b2ca0
Step 2/8 : EXPOSE 8500
 ---> Running in 3396aded0488
ERROR: Service 'tf-serving' failed to build: failed to start service utility VM (diff 3396aded04880d1c3e626f08ce534f5409e03fc941d5a416030df978cb454770): CreateComputeSystem 3396aded04880d1c3e626f08ce534f5409e03fc941d5a416030df978cb454770_svm: The virtual machine could not be started because a required feature is not installed.
(extra info: {"SystemType":"container","Name":"3396aded04880d1c3e626f08ce534f5409e03fc941d5a416030df978cb454770_svm","Layers":null,"HvPartition":true,"HvRuntime":{"ImagePath":"C:\\Program Files\\Linux Containers","LinuxInitrdFile":"initrd.img","LinuxKernelFile":"kernel"},"ContainerType":"linux","TerminateOnLastHandleClosed":true,"MappedVirtualDisks":[{"HostPath":"C:\\ProgramData\\docker\\lcow\\scratch\\3396aded04880d1c3e626f08ce534f5409e03fc941d5a416030df978cb454770.vhdx","ContainerPath":"/tmp/scratch","CreateInUtilityVM":true,"AttachOnly":false},{"HostPath":"C:\\ProgramData\\docker\\lcow\\3396aded04880d1c3e626f08ce534f5409e03fc941d5a416030df978cb454770\\sandbox.vhdx","ContainerPath":"/tmp/d2","CreateInUtilityVM":true,"ReadOnly":true,"AttachOnly":false}]})

```
I think this docker-compose issue is my local issue as I am running docker on a virtual machine. I'll investigate this further. 

Thanks for your help and fixing the issues quickly.

**Comment by carlomazzaferro** [comment] 2019-06-11 17:35
Yeah, as you noticed I took a break from developing this so thank to you for testing it all out. I'll do some extra testing on the first issue. It may be a Windows-specific issue, in which case you could give this a try: https://stackoverflow.com/a/32383309/2896045

Oh also, this project now comes with a UI Dashboard, which you can access using the `racket dashboard command`; that is one more of the things that need to be added to the documentation.

**Comment by prakashdaleyardi** [comment] 2019-06-12 03:44
Thanks for the info about 'racket dashboard'. Perhaps it is missing some file check-in. It shows default theme template right now. I'll start separate thread for this 'dashboard' discussion.

**Comment by prakashdaleyardi** [comment] 2019-06-12 04:27
I got myself a new physical machine. I didn't come across the issue mentioned above. But now I am stuck at `Creating tf.txt-serving ...`

More details below:
```
(racket) C:\racket\test1>docker-compose up --build -d
Creating network "test1_default" with the default driver
Building tf-serving
Step 1/8 : FROM tensorflow/serving
latest: Pulling from tensorflow/serving
6cf436f81810: Pull complete
987088a85b96: Pull complete
b4624b3efe06: Pull complete
d42beb8ded59: Pull complete
d0fb1b0e47a9: Pull complete
cc7e78af3eb6: Pull complete
f01c948950ed: Pull complete
7e8b55537522: Pull complete
Digest: sha256:df3c6fe1fbe5ccc3a916984ff313cc2d17e617f7b8782fc31e762c491325d813
Status: Downloaded newer image for tensorflow/serving:latest
 ---> 38bee21b2ca0
Step 2/8 : EXPOSE 8500
 ---> Running in e982126e14d7
Removing intermediate container e982126e14d7
 ---> 563afdb04f93
Step 3/8 : EXPOSE 8501
 ---> Running in cda7515debdb
Removing intermediate container cda7515debdb
 ---> a67aa5118e16
Step 4/8 : ENV MODEL_BASE_PATH=/models
 ---> Running in 2bef50aa50e7
Removing intermediate container 2bef50aa50e7
 ---> 83f6a752fcb8
Step 5/8 : RUN mkdir -p ${MODEL_BASE_PATH}
 ---> Running in 0ca7f143fb79
Removing intermediate container 0ca7f143fb79
 ---> fb6b7dd44c48
Step 6/8 : ENV MODEL_NAME=base
 ---> Running in 04de390ec263
Removing intermediate container 04de390ec263
 ---> cc2f79889a9d
Step 7/8 : RUN echo '#!/bin/bash \n\ntensorflow_model_server --port=8500 --rest_api_port=8501 --model_name=${MODEL_NAME} --model_base_path=${MODEL_BASE_PATH}/${MODEL_NAME} "$@"' > /usr/bin/tf_serving_entrypoint.sh && chmod +x /usr/bin/tf_serving_entrypoint.sh
 ---> Running in 36d3e347d797
Removing intermediate container 36d3e347d797
 ---> ff239131a82d
Step 8/8 : ENTRYPOINT ["/usr/bin/tf_serving_entrypoint.sh"]
 ---> Running in 482d77ef0992
Removing intermediate container 482d77ef0992
 ---> bc53712e1e79

Successfully built bc53712e1e79
Successfully tagged test1_tf-serving:latest
Creating tf.txt-serving ...

```

**Comment by prakashdaleyardi** [comment] 2019-06-12 04:56
I got myself a new physical machine. I didn't come across the docker-compose issue mentioned above with new machine.

**Closed** 2019-06-13 03:50 UTC
